name: Build and Deploy site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: borales/actions-yarn@v2.0.0
      - name: Yarn build
        run: yarn install
      - name: wasm-pack build
        run: wasm-pack build
      - name: yarn build
        run: yarn build
      - uses: actions/checkout@v2
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
